# Generated by Django 4.1.7 on 2023-03-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
