# Generated by Django 4.1.7 on 2023-03-24 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='favourites',
            field=models.ManyToManyField(blank=None, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
